name: Check for Updates

on:
  schedule:
    - cron: '0 0 * * 1,4'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Run script
        id: caddy-update
        shell: bash
        run: bash "${GITHUB_WORKSPACE}/scripts/caddy-update.sh"

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "Dockerfile"
          default_author: user_info
          message: "Update Caddy to ${{ steps.caddy-update.outputs.LATEST_CADDY_VERSION }}"
